### ISSUE TITLE
compiling as c++ lib

### ISSUE THREAD

**Issue by digitalist** [int010h/conan-luajit#1]
thanks for this recipe, I have just one question:
by default it compiles as C library and thus requires using `extern "C"`: 
```
extern "C" {
    #include <lua.h>
    #include <lualib.h>
    #include <lauxlib.h>
}
```
(http://lua-users.org/wiki/BuildingLua)

Is there a way to build luajit as c++ lib?

**Comment by int010h** [comment]
Hi, I guess this is not possible, luajit differs from classic lua implementation and does not support building as c++ library. You can use lua.hpp file, which will simply include ```extern "C"``` for you:
https://github.com/LuaJIT/LuaJIT/blob/master/src/lua.hpp

**Comment by digitalist** [comment]
thanks!

**Comment by digitalist** [comment]
ooh, maybe you can release a new bintray build please :-)
